name: Build and Push Docker Image

on:
  push:
    branches: main

env:
  IMAGE_NAME: tatev111/django-app-name
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ github.sha }}
      - name: Update Image Version
        id: imgupd
        uses: mikefarah/yq@master
        with:
           cmd: yq eval '.spec.template.spec.containers[0].image = "${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"' -i k8s/deployment.yaml
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
           commit_message: Apply image name changes      
      
